version: "3.9"

services:
  api:
    container_name: affiliates
    build: .
    ports:
      - 3001:3001
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB=${DB}
      - DB_USER=${DB_USER}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    container_name: db
    image: postgres:14
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

    volumes:
      - postgres_teste_fullstack:/var/lib/postgresql/data

volumes:
  postgres_teste_fullstack:
    driver: local